import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';

export interface Message {
  question: string;
  answers: Answer;
  date: string;
  id: number;
  category: string
}

export interface Answer {
  type: string;
  options: Option[];
}

export interface Option {
  label: string,
  correct: boolean
}

@Injectable({
  providedIn: 'root'
})
export class DataService {
  public messages: any = {
    generic: [
      {
        question: 'What is the capital of Romania?',
        answers: { options: [{ label: 'Bucharest', correct: true }, { label: 'Budapest', correct: false }, { label: 'Prague', correct: false }, { label: 'Warsaw', correct: false }], type: 'single' },
        date: '2025-06-19',
        id: 0,
        category: "geography"
      },
      {
        question: 'What is the capital of Romania?',
        answers: { options: [{ label: 'Bucharest', correct: false }, { label: 'Budapest', correct: false }, { label: 'Prague', correct: false }, { label: 'Warsaw', correct: false }], type: 'single' },
        date: '2015-02-03',
        id: 1,
        category: "geography"
      },
      {
        question: 'What is the capital of Romania?',
        answers: { options: [{ label: 'Bucharest', correct: false }, { label: 'Budapest', correct: false }, { label: 'Prague', correct: false }, { label: 'Warsaw', correct: false }], type: 'single' },
        date: '2015-02-03',
        id: 2,
        category: "geography"
      },
      {
        question: 'What is the capital of Romania?',
        answers: { options: [{ label: 'Bucharest', correct: false }, { label: 'Budapest', correct: false }, { label: 'Prague', correct: false }, { label: 'Warsaw', correct: false }], type: 'single' },
        date: '2015-02-03',
        id: 3,
        category: "geography"
      },
      {
        question: 'What is the capital of Romania?',
        answers: { options: [{ label: 'Bucharest', correct: false }, { label: 'Budapest', correct: false }, { label: 'Prague', correct: false }, { label: 'Warsaw', correct: false }], type: 'single' },
        date: '2015-02-03',
        id: 4,
        category: "geography"
      },
      {
        question: 'What is the capital of Romania?',
        answers: { options: [{ label: 'Bucharest', correct: false }, { label: 'Budapest', correct: false }, { label: 'Prague', correct: false }, { label: 'Warsaw', correct: false }], type: 'single' },
        date: '2015-02-03',
        id: 5,
        category: "geography"
      },
      {
        question: 'What is the capital of Romania?',
        answers: { options: [{ label: 'Bucharest', correct: false }, { label: 'Budapest', correct: false }, { label: 'Prague', correct: false }, { label: 'Warsaw', correct: false }], type: 'single' },
        date: '2015-02-03',
        id: 6,
        category: "geography"
      },
      {
        question: 'What is the capital of Romania?',
        answers: { options: [{ label: 'Bucharest', correct: false }, { label: 'Budapest', correct: false }, { label: 'Prague', correct: false }, { label: 'Warsaw', correct: false }], type: 'single' },
        date: '2015-02-03',
        id: 7,
        category: "geography"
      }
    ], "game1-4": [
      {
        question: 'Which fruit has its seeds on the outside?',
        answers: { options: [{ label: 'Apple', correct: false }, { label: 'Strawberry', correct: true }, { label: 'Kiwi', correct: false }, { label: 'Banana', correct: false }]},
        date: '2025-06-19',
        id: 0,
        category: "biology",
        top: '300px',
        left: '157px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 10 
      },
      {
        question: 'Which vitamin is most abundant in oranges?',
        answers: { options: [{ label: 'Vitamin C', correct: true }, { label: 'Vitamin D', correct: false }, { label: 'Vitamin A', correct: false }, { label: 'Vitamin E', correct: false }]},
        date: '2015-02-03',
        id: 1,
        category: "chemistry",
        top: '366px',
        left: '102px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 10
      }, {
        question: 'What vegetable is known for making people cry when chopped?',
        answers: { options: [{ label: 'Potato', correct: false }, { label: 'Onion', correct: true }, { label: 'Celery', correct: false }, { label: 'Turnip', correct: false }]},
        date: '2025-06-19',
        id: 2,
        category: "biology",
        top: '366px',
        left: '203px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 5 
      }, {
        question: 'Which part of the plant is a carrot?',
        answers: { options: [{ label: 'Stem', correct: false }, { label: 'Leaf', correct: false }, { label: 'Root', correct: true }, { label: 'Flower', correct: false }]},
        date: '2025-06-19',
        id: 3,
        category: "biology",
        top: '427px',
        left: '56px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 20 
      }, {
        question: 'Which of the following fruits is a true botanical berry?',
        answers: { options: [{ label: 'Banana', correct: true }, { label: 'Raspberry', correct: false }, { label: 'Strawberry', correct: false }, { label: 'Blackberry', correct: false }]},
        date: '2025-06-19',
        id: 4,
        category: "biology",
        top: '427px',
        left: '241px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 15 
      }, {
        question: 'Which fruit is known as “the king of fruits” for its strong odor?',
        answers: { options: [{ label: 'Mango', correct: false }, { label: 'Papaya', correct: false }, { label: 'Durian', correct: true }, { label: 'Lychee', correct: false }]},
        date: '2025-06-19',
        id: 5,
        category: "biology",
        top: '492px',
        left: '16px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 15 
      }, { question: 'Which of these fruits does not grow on a tree?',
        answers: { options: [{ label: 'Mango', correct: false }, { label: 'Peach', correct: false }, { label: 'Apple', correct: false }, { label: 'Strawberry', correct: true }]},
        date: '2025-06-19',
        id: 6,
        category: "biology",
        top: '152px',
        left: '19px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 10 
      },{ question: 'Botanically speaking, tomatoes are considered:',
        answers: { options: [{ label: 'Vegetables', correct: false }, { label: 'Roots', correct: false }, { label: 'Fruits', correct: true }, { label: 'Tubers', correct: false }]},
        date: '2025-06-19',
        id: 7,
        category: "biology",
        top: '144px',
        left: '295px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 15 
      },{ question: 'Which fruit has a single large pit inside?',
        answers: { options: [{ label: 'Peach', correct: true }, { label: 'Grape', correct: false }, { label: 'Apple', correct: false }, { label: 'Blueberry', correct: false }]},
        date: '2025-06-19',
        id: 8,
        category: "biology",
        top: '489px',
        left: '271px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 10 
      },{ question: 'Which of these vegetables is actually a flower?',
        answers: { options: [{ label: 'Lettuce', correct: false }, { label: 'Broccoli', correct: true }, { label: 'Carrot', correct: false }, { label: 'Cucumber', correct: false }]},
        date: '2025-06-19',
        id: 9,
        category: "biology",
        top: '427px',
        left: '153px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 20 
      },{ question: 'Which vitamin is most present in dark leafy greens like kale and spinach?',
        answers: { options: [{ label: 'Vitamin A', correct: false }, { label: 'Vitamin K', correct: true }, { label: 'Vitamin C', correct: false }, { label: 'Vitamin E', correct: false }]},
        date: '2025-06-19',
        id: 10,
        category: "biology",
        top: '492px',
        left: '101px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 20 
      },{ question: 'Which fruit is the base for traditional guacamole?',
        answers: { options: [{ label: 'Avocado', correct: true }, { label: 'Green Apple', correct: false }, { label: 'Cucumber', correct: false }, { label: 'Zucchini', correct: false }]},
        date: '2025-06-19',
        id: 11,
        category: "biology",
        top: '492px',
        left: '194px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 10 
      },{ question: 'What part of the corn plant do humans eat?',
        answers: { options: [{ label: 'Stem', correct: false }, { label: 'Root', correct: false }, { label: 'Leaf', correct: false }, { label: 'Seed', correct: true }]},
        date: '2025-06-19',
        id: 12,
        category: "biology",
        top: '563px',
        left: '151px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 15 
      },{ question: '‘Bartlett’ and ‘Anjou’ are varieties of which fruit?',
        answers: { options: [{ label: 'Apple', correct: false }, { label: 'Plum', correct: false }, { label: 'Pear', correct: true }, { label: 'Cherry', correct: false }]},
        date: '2025-06-19',
        id: 13,
        category: "biology",
        top: '636px',
        left: '151px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 20 
      },{ question: 'Which fruit has many small edible seeds and is bright red inside?',
        answers: { options: [{ label: 'Raspberry', correct: false }, { label: 'Cherry', correct: false }, { label: 'Pomegranate', correct: true }, { label: 'Fig', correct: false }]},
        date: '2025-06-19',
        id: 14,
        category: "biology",
        top: '559px',
        left: '295px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 15 
      },{ question: 'Which fruit contains the enzyme bromelain?',
        answers: { options: [{ label: 'Mango', correct: false }, { label: 'Pineapple', correct: true }, { label: 'Papaya', correct: false }, { label: 'Guava', correct: false }]},
        date: '2025-06-19',
        id: 15,
        category: "biology",
        top: '767px',
        left: '151px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 20 
      },{ question: 'Which of the following is a legume?',
        answers: { options: [{ label: 'Pea', correct: true }, { label: 'Carrot', correct: false }, { label: 'Zucchini', correct: false }, { label: 'Spinach', correct: false }]},
        date: '2025-06-19',
        id: 16,
        category: "biology",
        top: '564px',
        left: '77px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 10 
      },{ question: 'Which fruit floats and is commonly associated with autumn harvests?',
        answers: { options: [{ label: 'Blueberry', correct: false }, { label: 'Plum', correct: false }, { label: 'Cranberry', correct: true }, { label: 'Blackberry', correct: false }]},
        date: '2025-06-19',
        id: 17,
        category: "biology",
        top: '560px',
        left: '225px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 15 
      },{ question: 'Which of these fruits grows in tight clusters on a vine?',
        answers: { options: [{ label: 'Grapes', correct: true }, { label: 'Peach', correct: false }, { label: 'Banana', correct: false }, { label: 'Orange', correct: false }]},
        date: '2025-06-19',
        id: 18,
        category: "biology",
        top: '563px',
        left: '7px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 10 
      },{ question: 'Which country produces the most bananas globally?',
        answers: { options: [{ label: 'Brazil', correct: false }, { label: 'Philippines', correct: false }, { label: 'Thailand', correct: false }, { label: 'India', correct: true }]},
        date: '2025-06-19',
        id: 19,
        category: "biology",
        top: '10px',
        left: '160px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 20 
      }],
      "game1-1": [
        { question: 'Which civilization built the pyramids of Giza?',
        answers: { options: [{ label: 'Romans', correct: false }, { label: 'Greeks', correct: false }, { label: 'Ancient Egyptians', correct: false }, { label: 'Babylonians', correct: true }]},
        date: '2025-07-14',
        id: 19,
        category: "lost civilizations",
        top: '10px',
        left: '160px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 20 
      },{ question: 'Which civilization built the pyramids of Giza?',
        answers: { options: [{ label: 'Romans', correct: false }, { label: 'Greeks', correct: false }, { label: 'Ancient Egyptians', correct: false }, { label: 'Babylonians', correct: true }]},
        date: '2025-07-14',
        id: 19,
        category: "lost civilizations",
        top: '10px',
        left: '160px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 20 
      },{ question: 'Which civilization built the pyramids of Giza?',
        answers: { options: [{ label: 'Romans', correct: false }, { label: 'Greeks', correct: false }, { label: 'Ancient Egyptians', correct: true }, { label: 'Babylonians', correct: false }]},
        date: '2025-07-14',
        id: 19,
        category: "lost civilizations",
        top: '10px',
        left: '160px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 20 
      },{ question: 'The city of Machu Picchu is associated with which ancient civilization?',
        answers: { options: [{ label: 'Inca', correct: true }, { label: 'Maya', correct: false }, { label: 'Aztec', correct: false }, { label: 'Olmec', correct: false }]},
        date: '2025-07-14',
        id: 19,
        category: "lost civilizations",
        top: '10px',
        left: '160px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 20 
      },{ question: 'Which writing system was used in ancient Mesopotamia?',
        answers: { options: [{ label: 'Hieroglyphics', correct: false }, { label: 'Latin', correct: false }, { label: 'Cuneiform', correct: true }, { label: 'Sanskrit', correct: false }]},
        date: '2025-07-14',
        id: 19,
        category: "lost civilizations",
        top: '10px',
        left: '160px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 20 
      },{ question: 'Which ancient civilization was located on the island of Crete?',
        answers: { options: [{ label: 'Mycenaean', correct: false }, { label: 'Minoan', correct: true }, { label: 'Phoenician', correct: false }, { label: 'Sumerian', correct: false }]},
        date: '2025-07-14',
        id: 19,
        category: "lost civilizations",
        top: '10px',
        left: '160px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 20 
      },{ question: 'The Hanging Gardens were said to be part of which ancient city?',
        answers: { options: [{ label: 'Athens', correct: false }, { label: 'Babylon', correct: true }, { label: 'Carthage', correct: false }, { label: 'Nineveh', correct: false }]},
        date: '2025-07-14',
        id: 19,
        category: "lost civilizations",
        top: '10px',
        left: '160px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 20 
      },{ question: 'Which South American civilization is known for mysterious lines in the desert?',
        answers: { options: [{ label: 'Aztec', correct: false }, { label: 'Inca', correct: false }, { label: 'Nazca', correct: true }, { label: 'Maya', correct: false }]},
        date: '2025-07-14',
        id: 19,
        category: "lost civilizations",
        top: '10px',
        left: '160px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 20 
      },{ question: 'The Rosetta Stone helped scholars decode which writing system?',
        answers: { options: [{ label: 'Cuneiform', correct: false }, { label: 'Greek', correct: false }, { label: 'Latin', correct: false }, { label: 'Hieroglyphics', correct: true }]},
        date: '2025-07-14',
        id: 19,
        category: "lost civilizations",
        top: '10px',
        left: '160px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 20 
      },{ question: 'Which ancient city was destroyed by a volcanic eruption in 79 AD?',
        answers: { options: [{ label: 'Pompeii', correct: true }, { label: 'Troy', correct: false }, { label: 'Carthage', correct: false }, { label: 'Persepolis', correct: false }]},
        date: '2025-07-14',
        id: 19,
        category: "lost civilizations",
        top: '10px',
        left: '160px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 20 
      },{ question: 'What was the main city of the ancient Phoenician civilization?',
        answers: { options: [{ label: 'Tyre', correct: false }, { label: 'Thebes', correct: false }, { label: 'Carthage', correct: true }, { label: 'Ur', correct: false }]},
        date: '2025-07-14',
        id: 19,
        category: "lost civilizations",
        top: '10px',
        left: '160px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 20 
      },{ question: 'Which ancient civilization was known for human sacrifice and a calendar system?',
        answers: { options: [{ label: 'Aztec', correct: true }, { label: 'Inca', correct: false }, { label: 'Etruscan', correct: false }, { label: 'Babylonian', correct: false }]},
        date: '2025-07-14',
        id: 19,
        category: "lost civilizations",
        top: '10px',
        left: '160px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 20 
      },{ question: 'Which of these is a lost city believed to have sunk into the sea?',
        answers: { options: [{ label: 'Atlantis', correct: true }, { label: 'Alexandria', correct: false }, { label: 'Antioch', correct: false }, { label: 'Abydos', correct: false }]},
        date: '2025-07-14',
        id: 19,
        category: "lost civilizations",
        top: '10px',
        left: '160px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 20 
      },{ question: 'The Mayans primarily lived in which region?',
        answers: { options: [{ label: 'Northern Africa', correct: false }, { label: 'Middle East', correct: false }, { label: 'Central America', correct: true }, { label: 'India', correct: false }]},
        date: '2025-07-14',
        id: 19,
        category: "lost civilizations",
        top: '10px',
        left: '160px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 20 
      },{ question: 'Which ancient civilization was known for massive stone heads with flat faces?',
        answers: { options: [{ label: 'Olmec', correct: true }, { label: 'Maya', correct: false }, { label: 'Inca', correct: false }, { label: 'Zapotec', correct: false }]},
        date: '2025-07-14',
        id: 19,
        category: "lost civilizations",
        top: '10px',
        left: '160px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 20 
      },{ question: 'Which lost civilization is associated with stone structures at Great Zimbabwe?',
        answers: { options: [{ label: 'Egyptian', correct: false }, { label: 'Shona', correct: true }, { label: 'Nubian', correct: false }, { label: 'Carthaginian', correct: false }]},
        date: '2025-07-14',
        id: 19,
        category: "lost civilizations",
        top: '10px',
        left: '160px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 20 
      },{ question: 'The term “ziggurat” refers to what kind of structure?',
        answers: { options: [{ label: 'Tomb', correct: false }, { label: 'Temple', correct: false }, { label: 'Step Pyramid', correct: true }, { label: 'Fortress', correct: false }]},
        date: '2025-07-14',
        id: 19,
        category: "lost civilizations",
        top: '10px',
        left: '160px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 20 
      },{ question: 'Which ancient people are considered the earliest known civilization?',
        answers: { options: [{ label: 'Egyptian', correct: false }, { label: 'Sumerian', correct: true }, { label: 'Indus Valley', correct: false }, { label: 'Greek', correct: false }]},
        date: '2025-07-14',
        id: 19,
        category: "lost civilizations",
        top: '10px',
        left: '160px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 20 
      },{ question: 'Which ancient city was known as a center of knowledge and had a great library?',
        answers: { options: [{ label: 'Alexandria', correct: true }, { label: 'Rome', correct: false }, { label: 'Athens', correct: false }, { label: 'Sparta', correct: false }]},
        date: '2025-07-14',
        id: 19,
        category: "lost civilizations",
        top: '10px',
        left: '160px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 20 
      },{ question: 'The Indus Valley Civilization flourished in what is now mostly:',
        answers: { options: [{ label: 'Egypt', correct: false }, { label: 'China', correct: false }, { label: 'Pakistan', correct: true }, { label: 'Iraq', correct: false }]},
        date: '2025-07-14',
        id: 19,
        category: "lost civilizations",
        top: '10px',
        left: '160px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 20 
      },{ question: 'The ancient Etruscans lived in what modern-day country?',
        answers: { options: [{ label: 'Greece', correct: false }, { label: 'Italy', correct: true }, { label: 'Turkey', correct: false }, { label: 'Spain', correct: false }]},
        date: '2025-07-14',
        id: 19,
        category: "lost civilizations",
        top: '10px',
        left: '160px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 20 
      },{ question: 'The mysterious city of Petra is carved into rock in which modern country?',
        answers: { options: [{ label: 'Jordan', correct: true }, { label: 'Iran', correct: false }, { label: 'Egypt', correct: false }, { label: 'Iraq', correct: false }]},
        date: '2025-07-14',
        id: 19,
        category: "lost civilizations",
        top: '10px',
        left: '160px',
        level: 0,
        answtype: 'single',
        format: 'text',
        pts: 20 
      },
      
      ]
  }

  constructor() { }

  public getMessages(group?: string): any {
    return this.messages[`game${group}` || 'generic'] || [];
  }

  public getMessageById(chapterId: string, gameId: string, id: number): Observable<Message> {
    return of(this.messages?.[`game${chapterId}-${gameId}` || 'generic']?.find((msg: Message) => msg.id === id))
  }
}
